incorporated Index into build_schema method
Tested on KY staff data. The validation tests pass for participant. But Fail on demographic types -- raising a Schema error with description. TODO: add coerce argument to DataFrameSchema and (for KY staff need to map Unknown.
SchemaError: <Schema Column(name=gender, type=DataType(str))> failed element-wise validator 0:
<Check isin: isin({'Gender nonconforming', 'Something else', 'Female', 'Not reported', 'Transgender', 'Male'})>
failure cases:
  index failure_case
0    9D      Unknown
1   28D      Unknown